# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IgB0vSEvSh6MipX8Um165wWwOsasN3PX
"""

'''
Nome: João Vítor Brito da Silveira

Método: Método Iterativo de Gauss-Seidel

Resumo: O Método de Gauss-Seidel é uma técnica iterativa utilizada
para resolver sistemas de equações lineares. É um dos métodos mais comuns
para encontrar soluções aproximadas em problemas de álgebra linear,
especialmente quando lidamos com grandes sistemas de equações.

'''

import numpy as np

def gauss_seidel(A, b, x0=None, tol=0.05, max_iter=100):

#Resolve o sistema Ax = b usando o método de Gauss-Seidel.
#A (numpy.ndarray): Matriz de coeficientes.
#b (numpy.ndarray): Vetor dos termos constantes.
#x0 (numpy.ndarray): Estimativa inicial das soluções (opcional).
#tol (float): Tolerância para o critério de parada.
#max_iter (int): Número máximo de iterações.
#numpy.ndarray: Solução do sistema.

    n=len(b)  #Número de equações
    x=np.copy(x0) if x0 is not None else np.zeros(n)  #Inicialização do vetor de solução
    for _ in range(max_iter):
        x_velho=np.copy(x)  #Armazena a solução anterior para comparação
        for i in range(n):
            sigma=sum(A[i][j]*x[j] for j in range(n) if j!=i)  #Calcula a soma dos termos conhecidos
            x[i]=(b[i]-sigma)/A[i][i]  #Atualiza a solução para a i-ésima variável
        #Verifica a convergência
        if np.linalg.norm(x-x_velho, ord=np.inf)/np.linalg.norm(x, ord=np.inf)<tol:
            return x
    return x

#Definição da matriz de coeficientes e do vetor de constantes
A=np.array([[15, -3, -1], [-3, 18, -6], [-4, -1, 12]], dtype=float)
b=np.array([3800, 1200, 2350], dtype=float)
x0=np.zeros(3)  #Estimativa inicial

#Solução usando Gauss-Seidel
solucao_gs=gauss_seidel(A, b, x0=x0)
print("Solução de Gauss-Seidel:", solucao_gs)

A2=np.array([[10, 2, -1], [-3, -6, 2], [1, 1, 5]], dtype=float)
b2=np.array([27, -61.5, -21.5], dtype=float)
x0_2=np.zeros(3)

solucao_gs_2=gauss_seidel(A2, b2, x0=x0_2)
print("Solução de Gauss-Seidel para o segundo sistema:", solucao_gs_2)