# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QxvFg7Aq_XybQttdiOV3J_17tTqxFwbn
"""

'''
Aluno: João Vítor Brito da Silveira

Método: Eliminação Gaussiana

Resumo: A eliminação gaussiana, também conhecida como escalonamento, é um método direto para resolver sistemas lineares.
Apesar de ser um dos métodos mais antigos para resolver equações simultâneas, mantém-se como um dos algoritmos mais importantes.
Consiste em um algoritmo para eliminar variáveis (formandoum sistema triangular superior) e substituir regressivamente.

'''

#importando funções matemáticas
import numpy as np

#Definindo função
def eliminacao_gaussiana(A, b):
    n=len(b)
    #Criar a matriz aumentada
    Ab=np.hstack((A, b.reshape(-1, 1)))

    #Eliminação progressiva
    #Para cada pivô k, percorre as linhas abaixo do pivô i e calcula o fator.
    #Atualiza as linhas abaixo do pivô subtraindo o fator multiplicado pela linha do pivô.
    for k in range(n-1):
        for i in range(k+1,n):
            fator=Ab[i, k]/Ab[k, k]
            Ab[i, k+1:]=Ab[i, k+1:]-fator*Ab[k, k+1:]
            #Zerando a posição que foi eliminada
            Ab[i, k]=0
            b[i]=b[i]-fator*b[k]

    #Substituição regressiva
    #Resolve o sistema triangular superior obtido na eliminação progressiva.
    #Para cada linha i, começa da última linha e trabalha de volta para cima, acumulando a soma dos produtos dos coeficientes e das soluções já encontradas.

    x=np.zeros(n)
    x[-1]=Ab[-1, -1]/Ab[-1, -2]
    for i in range(n-2, -1, -1):
        soma=Ab[i, -1]
        for j in range(i+1, n):
            soma-=Ab[i, j]*x[j]
        x[i]=soma/Ab[i, i]

    return x

#Definindo o sistema de equações
#A é a matriz de coeficientes.
#b é o vetor dos termos independentes.
A = np.array([
    [3, -0.1, -0.2],
    [0.1, 7, -0.3],
    [0.3, -0.2, 10]
], dtype=float)

b=np.array([7.85, -19.3, 71.4], dtype=float)

#Resolvendo o sistema
#A função eliminacao_gaussiana resolve o sistema.
#A solução é impressa com seis algarismos significativos.
sol=eliminacao_gaussiana(A, b)

#Imprimindo a solução com seis algarismos significativos
print("Solução:")
for i, x in enumerate(sol):
    print(f"x{i+1}={x:.6g}")