# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18CRQO13SZmsOWgPjjXh3J5froyasBL2g
"""

'''
Nome: João Vítor Brito da Silveira

Método: 1/3 de Simpsom

Resumo: A regra de 1/3 de Simpsom é uma técnica utilizada para aproximar o valor
de uma integral definida. Ele é uma forma mais precisa que outros métodos
simples, como a Regra dos Trapézios, para calcular a integral de uma função
quando o cálculo exato é difícil ou impossível.

Esse método funciona dividindo o intervalo de integração em um número par de
subintervalos, e em seguida, aplicando uma parábola para aproximar a área sob
a curva da função em cada par de subintervalos. Especificamente, o método de
Simpson usa uma combinação ponderada dos valores da função nos pontos inicial,
final e no ponto médio de cada par de subintervalos.
'''

#Definindo a função que será integrada
def f(x):

    return 0.2+25*x-200*x**2+675*x**3-900*x**4+400*x**5

#Implementando o método de 1/3 de Simpson
def simpson(a, b, n):
    #Calcular o tamanho do subintervalo
    h=(b-a)/n

    #Inicializando as somas para valores da função nos pontos pares e ímpares
    soma_pares=0
    soma_impares=0

    #Iterabdo sobre os pontos do intervalo, excluindo o primeiro e o último
    for i in range(1, n):
        x_i=a+i*h  #Calcular a posição do ponto atual
        if i%2==0: #Se o índice for par
            soma_pares+=f(x_i)
        else: #Se o índice for ímpar
            soma_impares+=f(x_i)

    #Aplicando a fórmula da Regra 1/3 de Simpson
    #I=(h/3)*[f(a)+4*soma_impares+2*soma_pares+f(b)]
    I=(h/3)*(f(a)+4*soma_impares+2*soma_pares+f(b))

    #Retornando para o valor calculado da integral
    return I

#Definindp os limites do intervalo de integração e o número de subintervalos
a=0 #Limite inferior
b=0.8 #Limite superior
n=4 #Número de subintervalos (deve ser par)

#Calculanso a integral usando a regra de Simpson
resultado=simpson(a, b, n)

#Valor verdadeiro da integral dado no exemplo
valor_verdadeiro=1.640533

#Calculando o erro absoluto verdadeiro
erro_absoluto=abs(valor_verdadeiro-resultado)

#Imprimindo os resultados
print(f"Resultado da integração: {resultado}")
print(f"Erro absoluto verdadeiro: {erro_absoluto}")