# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGiu6SbI7tG9L-KRnaj9FGVaQTfXAmCb
"""

'''
Nome: João Vítor Brito da Silveira

Método: Regressão Polinomial

Resumo: A regressão polinomial é uma extensão do método de regressão linear,
utilizada quando os dados apresentam uma relação não linear entre a variável
independente (X) e a variável dependente (Y). Nesse método, a relação entre
as variáveis é modelada como uma função polinomial de ordem
n, ou seja, em vez de ajustar uma linha reta aos dados,
ajusta-se uma curva polinomial.
'''

#Importando funções matemáticas
import numpy as np

def regressao_polinomial(x, y, m):
    #Determina o número de pontos
    n=len(x)

    #Verifica se há dados suficientes para ajustar o polinômio de ordem m
    if n<m+1:
        raise ValueError("Erro: A regressão é impossível com o número de dados fornecidos.")

    #Inicializa a matriz A e o vetor b com zeros
    A=np.zeros((m+1, m+1)) #Matriz do sistema de equações normais
    b=np.zeros(m+1) #Vetor do lado direito da equação normal

    #Calcular os elementos da equação normal
    for i in range(m+1):
        for j in range(i+1):
            k=i+j #Índice para a soma das potências de x
            #Calcula o somatório dos elementos da matriz A
            soma=sum(x**k)
            A[i,j]=soma
            A[j,i]=soma #Aproveita a simetria da matriz A

        #Calcula o somatório para o vetor b
        soma=sum(y*x**i)
        b[i]=soma

    #Resolve o sistema de equações lineares para encontrar os coeficientes do polinômio
    coef=np.linalg.solve(A, b)

    return coef

#Exemplo de uso com os dados fornecidos no documento
x=np.array([0, 1, 2, 3, 4, 5]) #Valores de x
y=np.array([2.1, 7.7, 13.6, 27.2, 40.9, 61.1]) #Valores correspondentes de y

#Ordem do polinômio que queremos ajustar
m=2

#Chama a função para calcular os coeficientes do polinômio
coeficientes=regressao_polinomial(x, y, m)

#Exibe os coeficientes encontrados
print("Coeficientes do polinômio:")
for i, coef in enumerate(coeficientes):
    print(f"a{i}={coef:.4f}")